export const mathChu1FirstQuestions = [
  // 正負の数：概念・絶対値・大小関係 (1〜10)
  { id: 'math-chu1-first-0001', subject: 'math', grade: 'chu1', term: 'first', text: `0より5小さい数はどれか。`, choices: ["-5","5","0","-10"], correctIndex: 0, explanation: `0から5を引いた数なので、-5になります。` },
  { id: 'math-chu1-first-0002', subject: 'math', grade: 'chu1', term: 'first', text: `基準を0として、3大きい数を+3と表すとき、4小さい数はどう表すか。`, choices: ["+4","-4","-1","-7"], correctIndex: 1, explanation: `小さい数は負の符号「-」を使って表すため、-4となります。` },
  { id: 'math-chu1-first-0003', subject: 'math', grade: 'chu1', term: 'first', text: `絶対値が3である数はどれか。`, choices: ["3のみ","-3のみ","3と-3","0と3"], correctIndex: 2, explanation: `絶対値は数直線上で0からの距離を表します。0から3離れている数は3と-3の2つあります。` },
  { id: 'math-chu1-first-0004', subject: 'math', grade: 'chu1', term: 'first', text: `-5の絶対値はどれか。`, choices: ["-5","0","5","-1/5"], correctIndex: 2, explanation: `数直線上で-5から0までの距離は5です。` },
  { id: 'math-chu1-first-0005', subject: 'math', grade: 'chu1', term: 'first', text: `次の不等式のうち、正しいものはどれか。`, choices: ["-3 < -5","-3 > -5","-3 = -5","-5 > 0"], correctIndex: 1, explanation: `負の数は絶対値が小さいほど大きくなるため、-3の方が-5より大きいです。` },
  { id: 'math-chu1-first-0006', subject: 'math', grade: 'chu1', term: 'first', text: `-1/2 と -1/3 の大小関係を正しく表したものはどれか。`, choices: ["-1/2 > -1/3","-1/2 < -1/3","-1/2 = -1/3","比べられない"], correctIndex: 1, explanation: `通分すると -3/6 と -2/6 になります。負の数は絶対値が小さい方が大きいので、-1/2 < -1/3 です。` },
  { id: 'math-chu1-first-0007', subject: 'math', grade: 'chu1', term: 'first', text: `負の数の中で、最も大きい整数はどれか。`, choices: ["0","-1","-10","-99"], correctIndex: 1, explanation: `0は負の数ではありません。負の整数で最も0に近い（最も大きい）のは-1です。` },
  { id: 'math-chu1-first-0008', subject: 'math', grade: 'chu1', term: 'first', text: `絶対値が2より小さい整数は全部で何個あるか。`, choices: ["2個","3個","4個","5個"], correctIndex: 1, explanation: `絶対値が2より小さい整数は、-1、0、1の3つです。` },
  { id: 'math-chu1-first-0009', subject: 'math', grade: 'chu1', term: 'first', text: `東へ3km進むことを+3kmと表すとき、西へ2km進むことはどう表すか。`, choices: ["+2km","-2km","+5km","-5km"], correctIndex: 1, explanation: `西は東の反対方向なので、負の符号を使って-2kmと表します。` },
  { id: 'math-chu1-first-0010', subject: 'math', grade: 'chu1', term: 'first', text: `体重が1kg減ることを-1kgと表すなら、+2kgは何を表しているか。`, choices: ["体重が2kg減ること","体重が1kg増えること","体重が2kg増えること","体重が変わらないこと"], correctIndex: 2, explanation: `正の符号は負の符号と反対の性質（この場合は増加）を表すため、2kg増えることを意味します。` },

  // 正負の数：加法と減法 (11〜20)
  { id: 'math-chu1-first-0011', subject: 'math', grade: 'chu1', term: 'first', text: `(+3) + (+5) を計算しなさい。`, choices: ["2","8","-2","-8"], correctIndex: 1, explanation: `同符号の加法です。+(3+5) = 8 になります。` },
  { id: 'math-chu1-first-0012', subject: 'math', grade: 'chu1', term: 'first', text: `(-4) + (-6) を計算しなさい。`, choices: ["-2","2","10","-10"], correctIndex: 3, explanation: `同符号の加法です。-(4+6) = -10 になります。` },
  { id: 'math-chu1-first-0013', subject: 'math', grade: 'chu1', term: 'first', text: `(+7) + (-2) を計算しなさい。`, choices: ["5","-5","9","-9"], correctIndex: 0, explanation: `異符号の加法です。絶対値の大きい方の符号がつき、絶対値の差を計算して +(7-2) = 5 になります。` },
  { id: 'math-chu1-first-0014', subject: 'math', grade: 'chu1', term: 'first', text: `(-8) + (+5) を計算しなさい。`, choices: ["-13","13","-3","3"], correctIndex: 2, explanation: `異符号の加法です。絶対値の大きい負の符号がつき、-(8-5) = -3 になります。` },
  { id: 'math-chu1-first-0015', subject: 'math', grade: 'chu1', term: 'first', text: `(-3) - (+4) を計算しなさい。`, choices: ["-7","1","-1","7"], correctIndex: 0, explanation: `ひき算は足し算に直します。(-3) + (-4) となり、答えは-7です。` },
  { id: 'math-chu1-first-0016', subject: 'math', grade: 'chu1', term: 'first', text: `(+5) - (-2) を計算しなさい。`, choices: ["3","-3","7","-7"], correctIndex: 2, explanation: `ひき算は符号を変えて足し算に直します。(+5) + (+2) = 7 となります。` },
  { id: 'math-chu1-first-0017', subject: 'math', grade: 'chu1', term: 'first', text: `(-6) - (-6) を計算しなさい。`, choices: ["-12","12","0","-36"], correctIndex: 2, explanation: `(-6) + (+6) となり、絶対値が同じで異符号の和は0になります。` },
  { id: 'math-chu1-first-0018', subject: 'math', grade: 'chu1', term: 'first', text: `0 - (-5) を計算しなさい。`, choices: ["-5","5","0","1/5"], correctIndex: 1, explanation: `0 + (+5) となり、答えは5です。` },
  { id: 'math-chu1-first-0019', subject: 'math', grade: 'chu1', term: 'first', text: `3 - 8 + 2 を計算しなさい。`, choices: ["3","-3","7","-7"], correctIndex: 1, explanation: `左から順に計算します。(3 - 8) + 2 = -5 + 2 = -3 です。` },
  { id: 'math-chu1-first-0020', subject: 'math', grade: 'chu1', term: 'first', text: `-5 - (-3) + 7 を計算しなさい。`, choices: ["5","-5","9","-9"], correctIndex: 0, explanation: `-5 + 3 + 7 = -2 + 7 = 5 となります。` },

  // 正負の数：乗法と除法 (21〜30)
  { id: 'math-chu1-first-0021', subject: 'math', grade: 'chu1', term: 'first', text: `(+3) × (+4) を計算しなさい。`, choices: ["7","12","-7","-12"], correctIndex: 1, explanation: `同符号の乗法は正の数になります。+ (3 × 4) = 12 です。` },
  { id: 'math-chu1-first-0022', subject: 'math', grade: 'chu1', term: 'first', text: `(-5) × (-6) を計算しなさい。`, choices: ["-30","11","-11","30"], correctIndex: 3, explanation: `同符号（負の数どうし）の乗法は正の数になります。+ (5 × 6) = 30 です。` },
  { id: 'math-chu1-first-0023', subject: 'math', grade: 'chu1', term: 'first', text: `(+8) × (-2) を計算しなさい。`, choices: ["16","-16","6","-6"], correctIndex: 1, explanation: `異符号の乗法は負の数になります。- (8 × 2) = -16 です。` },
  { id: 'math-chu1-first-0024', subject: 'math', grade: 'chu1', term: 'first', text: `(-7) × (+3) を計算しなさい。`, choices: ["21","-21","4","-10"], correctIndex: 1, explanation: `異符号の乗法は負の数になります。- (7 × 3) = -21 です。` },
  { id: 'math-chu1-first-0025', subject: 'math', grade: 'chu1', term: 'first', text: `(-12) ÷ (+3) を計算しなさい。`, choices: ["-4","4","-9","-36"], correctIndex: 0, explanation: `異符号の除法は負の数になります。- (12 ÷ 3) = -4 です。` },
  { id: 'math-chu1-first-0026', subject: 'math', grade: 'chu1', term: 'first', text: `(+24) ÷ (-6) を計算しなさい。`, choices: ["4","-4","18","-144"], correctIndex: 1, explanation: `異符号の除法は負の数になります。- (24 ÷ 6) = -4 です。` },
  { id: 'math-chu1-first-0027', subject: 'math', grade: 'chu1', term: 'first', text: `(-15) ÷ (-5) を計算しなさい。`, choices: ["3","-3","10","-10"], correctIndex: 0, explanation: `同符号の除法は正の数になります。+ (15 ÷ 5) = 3 です。` },
  { id: 'math-chu1-first-0028', subject: 'math', grade: 'chu1', term: 'first', text: `0 ÷ (-4) を計算しなさい。`, choices: ["-4","4","0","計算できない"], correctIndex: 2, explanation: `0を0以外のどんな数で割っても、答えは0になります。` },
  { id: 'math-chu1-first-0029', subject: 'math', grade: 'chu1', term: 'first', text: `(-2) × (-3) × (-4) を計算しなさい。`, choices: ["24","-24","9","-9"], correctIndex: 1, explanation: `負の数が奇数個（3つ）かけられているので、答えの符号はマイナスになります。-(2×3×4) = -24。` },
  { id: 'math-chu1-first-0030', subject: 'math', grade: 'chu1', term: 'first', text: `(-12) × 0 を計算しなさい。`, choices: ["-12","12","0","1"], correctIndex: 2, explanation: `どんな数に0をかけても、答えは0になります。` },

  // 正負の数：累乗 (31〜40)
  { id: 'math-chu1-first-0031', subject: 'math', grade: 'chu1', term: 'first', text: `3² を計算しなさい。`, choices: ["6","-6","9","-9"], correctIndex: 2, explanation: `3² は 3 × 3 を意味します。3 × 3 = 9 です。` },
  { id: 'math-chu1-first-0032', subject: 'math', grade: 'chu1', term: 'first', text: `(-4)² を計算しなさい。`, choices: ["16","-16","8","-8"], correctIndex: 0, explanation: `カッコごと2乗するので、(-4) × (-4) = 16 になります。` },
  { id: 'math-chu1-first-0033', subject: 'math', grade: 'chu1', term: 'first', text: `-4² を計算しなさい。`, choices: ["16","-16","8","-8"], correctIndex: 1, explanation: `マイナスはそのままで4だけを2乗します。-(4 × 4) = -16 になります。` },
  { id: 'math-chu1-first-0034', subject: 'math', grade: 'chu1', term: 'first', text: `(-2)³ を計算しなさい。`, choices: ["6","-6","8","-8"], correctIndex: 3, explanation: `(-2) × (-2) × (-2) = -8 となります。` },
  { id: 'math-chu1-first-0035', subject: 'math', grade: 'chu1', term: 'first', text: `-2³ を計算しなさい。`, choices: ["8","-8","6","-6"], correctIndex: 1, explanation: `マイナスはそのままで2を3乗します。-(2 × 2 × 2) = -8 になります。` },
  { id: 'math-chu1-first-0036', subject: 'math', grade: 'chu1', term: 'first', text: `(-1)¹⁰⁰ を計算しなさい。`, choices: ["1","-1","100","-100"], correctIndex: 0, explanation: `負の数を偶数回（100回）かけるので、符号はプラスになります。1は何度かけても1です。` },
  { id: 'math-chu1-first-0037', subject: 'math', grade: 'chu1', term: 'first', text: `-1¹⁰¹ を計算しなさい。`, choices: ["1","-1","101","-101"], correctIndex: 1, explanation: `マイナスはそのままで、1を101乗します。-(1) = -1 となります。` },
  { id: 'math-chu1-first-0038', subject: 'math', grade: 'chu1', term: 'first', text: `2³ × 3 を計算しなさい。`, choices: ["18","24","36","48"], correctIndex: 1, explanation: `先に累乗を計算します。8 × 3 = 24 です。` },
  { id: 'math-chu1-first-0039', subject: 'math', grade: 'chu1', term: 'first', text: `(-3)² × (-2) を計算しなさい。`, choices: ["18","-18","36","-36"], correctIndex: 1, explanation: `(-3)² = 9。これに-2をかけるので、9 × (-2) = -18 となります。` },
  { id: 'math-chu1-first-0040', subject: 'math', grade: 'chu1', term: 'first', text: `-3² × (-2)² を計算しなさい。`, choices: ["36","-36","18","-18"], correctIndex: 1, explanation: `-3² = -9、(-2)² = 4 です。よって、(-9) × 4 = -36 となります。` },

  // 正負の数：四則混合計算 (41〜50)
  { id: 'math-chu1-first-0041', subject: 'math', grade: 'chu1', term: 'first', text: `5 + 3 × (-2) を計算しなさい。`, choices: ["-1","1","-16","16"], correctIndex: 0, explanation: `かけ算を先に計算します。5 + (-6) = -1 です。` },
  { id: 'math-chu1-first-0042', subject: 'math', grade: 'chu1', term: 'first', text: `12 - (-4) × 2 を計算しなさい。`, choices: ["20","4","32","-4"], correctIndex: 0, explanation: `かけ算を先に計算します。12 - (-8) = 12 + 8 = 20 です。` },
  { id: 'math-chu1-first-0043', subject: 'math', grade: 'chu1', term: 'first', text: `(-10) ÷ 2 - 4 を計算しなさい。`, choices: ["-9","1","-1","9"], correctIndex: 0, explanation: `わり算を先に計算します。-5 - 4 = -9 です。` },
  { id: 'math-chu1-first-0044', subject: 'math', grade: 'chu1', term: 'first', text: `8 + (-12) ÷ (-3) を計算しなさい。`, choices: ["12","4","-4","-12"], correctIndex: 0, explanation: `わり算を先に計算します。8 + 4 = 12 です。` },
  { id: 'math-chu1-first-0045', subject: 'math', grade: 'chu1', term: 'first', text: `(3 - 7) × 2 を計算しなさい。`, choices: ["-8","8","-11","11"], correctIndex: 0, explanation: `カッコの中を先に計算します。(-4) × 2 = -8 です。` },
  { id: 'math-chu1-first-0046', subject: 'math', grade: 'chu1', term: 'first', text: `15 ÷ (2 - 5) を計算しなさい。`, choices: ["-5","5","12","-12"], correctIndex: 0, explanation: `カッコの中を先に計算します。15 ÷ (-3) = -5 です。` },
  { id: 'math-chu1-first-0047', subject: 'math', grade: 'chu1', term: 'first', text: `-2² + 5 × 3 を計算しなさい。`, choices: ["11","19","-1","-11"], correctIndex: 0, explanation: `累乗とかけ算を先に計算します。-4 + 15 = 11 です。` },
  { id: 'math-chu1-first-0048', subject: 'math', grade: 'chu1', term: 'first', text: `(-3)² - 4 × (-2) を計算しなさい。`, choices: ["17","1","-1","-17"], correctIndex: 0, explanation: `累乗とかけ算を計算します。9 - (-8) = 9 + 8 = 17 です。` },
  { id: 'math-chu1-first-0049', subject: 'math', grade: 'chu1', term: 'first', text: `10 - 2 × (3 - 5)² を計算しなさい。`, choices: ["2","18","-6","32"], correctIndex: 0, explanation: `カッコの中の計算→累乗→かけ算の順に行います。10 - 2 × (-2)² = 10 - 2 × 4 = 10 - 8 = 2。` },
  { id: 'math-chu1-first-0050', subject: 'math', grade: 'chu1', term: 'first', text: `(-4) ÷ 2 - (-3)² を計算しなさい。`, choices: ["-11","7","-7","11"], correctIndex: 0, explanation: `(-4) ÷ 2 = -2、(-3)² = 9。よって -2 - 9 = -11 となります。` },

  // 素数と素因数分解 (51〜60)
  { id: 'math-chu1-first-0051', subject: 'math', grade: 'chu1', term: 'first', text: `次のうち、素数であるものはどれか。`, choices: ["1","2","9","15"], correctIndex: 1, explanation: `素数は「1とその数自身のほかに約数を持たない自然数（ただし1は除く）」です。2は唯一の偶数の素数です。` },
  { id: 'math-chu1-first-0052', subject: 'math', grade: 'chu1', term: 'first', text: `1から10までの自然数の中に素数はいくつあるか。`, choices: ["3個","4個","5個","6個"], correctIndex: 1, explanation: `2, 3, 5, 7 の4個です。1は素数に含まれません。` },
  { id: 'math-chu1-first-0053', subject: 'math', grade: 'chu1', term: 'first', text: `12を素因数分解した式として正しいものはどれか。`, choices: ["2 × 6","3 × 4","2² × 3","2 × 3²"], correctIndex: 2, explanation: `素数だけの積で表します。12 = 2 × 2 × 3 = 2² × 3 です。` },
  { id: 'math-chu1-first-0054', subject: 'math', grade: 'chu1', term: 'first', text: `30を素因数分解した式として正しいものはどれか。`, choices: ["5 × 6","2 × 15","2 × 3 × 5","2² × 7"], correctIndex: 2, explanation: `素数で順に割っていくと、30 = 2 × 3 × 5 となります。` },
  { id: 'math-chu1-first-0055', subject: 'math', grade: 'chu1', term: 'first', text: `45を素因数分解した式として正しいものはどれか。`, choices: ["5 × 9","3² × 5","3 × 15","3 × 5²"], correctIndex: 1, explanation: `45 = 3 × 3 × 5 = 3² × 5 となります。` },
  { id: 'math-chu1-first-0056', subject: 'math', grade: 'chu1', term: 'first', text: `60を素因数分解した式として正しいものはどれか。`, choices: ["2² × 3 × 5","2 × 3² × 5","2 × 3 × 10","4 × 3 × 5"], correctIndex: 0, explanation: `60 = 2 × 2 × 3 × 5 = 2² × 3 × 5 です。10や4は素数ではありません。` },
  { id: 'math-chu1-first-0057', subject: 'math', grade: 'chu1', term: 'first', text: `素因数分解が 2³ × 3 となる自然数はどれか。`, choices: ["12","18","24","36"], correctIndex: 2, explanation: `2³ = 8 なので、8 × 3 = 24 となります。` },
  { id: 'math-chu1-first-0058', subject: 'math', grade: 'chu1', term: 'first', text: `18にできるだけ小さい自然数をかけて、ある自然数の2乗にしたい。何をかければよいか。`, choices: ["2","3","4","6"], correctIndex: 0, explanation: `18 = 2 × 3² です。ある数の2乗にするには、各素因数の指数が偶数になる必要があります。足りないのは2が1つです。` },
  { id: 'math-chu1-first-0059', subject: 'math', grade: 'chu1', term: 'first', text: `50にできるだけ小さい自然数をかけて、ある自然数の2乗にしたい。何をかければよいか。`, choices: ["2","3","5","10"], correctIndex: 0, explanation: `50 = 2 × 5² です。2乗の形にするためには、2をもう1つかけて 2² にする必要があります。` },
  { id: 'math-chu1-first-0060', subject: 'math', grade: 'chu1', term: 'first', text: `次のうち、素数でないものはどれか。`, choices: ["13","17","19","21"], correctIndex: 3, explanation: `21は3や7で割り切れるため、素数ではありません（21 = 3 × 7）。` },

  // 文字の式のルール (61〜70)
  { id: 'math-chu1-first-0061', subject: 'math', grade: 'chu1', term: 'first', text: `a × 5 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["a5","5a","5×a","a×5"], correctIndex: 1, explanation: `文字の式では「×」を省き、数は文字の前に書きます。` },
  { id: 'math-chu1-first-0062', subject: 'math', grade: 'chu1', term: 'first', text: `x × (-3) を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["-x3","x-3","-3x","3-x"], correctIndex: 2, explanation: `負の数でも文字の前に置きます。-3x となります。` },
  { id: 'math-chu1-first-0063', subject: 'math', grade: 'chu1', term: 'first', text: `b × 1 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["1b","b","b1","b×1"], correctIndex: 1, explanation: `係数の1は書かずに省略します。` },
  { id: 'math-chu1-first-0064', subject: 'math', grade: 'chu1', term: 'first', text: `c × (-1) を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["-1c","-c","c-1","c-"], correctIndex: 1, explanation: `係数の1は省略するため、-c と書きます。` },
  { id: 'math-chu1-first-0065', subject: 'math', grade: 'chu1', term: 'first', text: `x × y × x を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["xxy","yx²","x²y","2xy"], correctIndex: 2, explanation: `同じ文字の積は累乗の指数を使い、アルファベット順に書きます。` },
  { id: 'math-chu1-first-0066', subject: 'math', grade: 'chu1', term: 'first', text: `a ÷ 3 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["3/a","a/3","3a","a ÷ 3"], correctIndex: 1, explanation: `わり算は「÷」を使わず、分数の形で表します。割られる数(a)が分子になります。` },
  { id: 'math-chu1-first-0067', subject: 'math', grade: 'chu1', term: 'first', text: `(x + y) ÷ 5 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["(x+y)/5","5/(x+y)","x + y/5","x/5 + y"], correctIndex: 0, explanation: `(x+y)全体が分子になります。分数の形にしたときはカッコを外します。` },
  { id: 'math-chu1-first-0068', subject: 'math', grade: 'chu1', term: 'first', text: `a × 2 + b × 3 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["5ab","2a + 3b","a2 + b3","2a3b"], correctIndex: 1, explanation: `かけ算の部分だけを「×」を省いてそれぞれまとめます。足し算の「+」は省きません。` },
  { id: 'math-chu1-first-0069', subject: 'math', grade: 'chu1', term: 'first', text: `x ÷ 4 - y × 2 を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["x/4 - 2y","4/x - y2","(x-y)/4","x/(4-2y)"], correctIndex: 0, explanation: `わり算は分数に、かけ算は「×」を省いてまとめます。ひき算の「-」はそのままです。` },
  { id: 'math-chu1-first-0070', subject: 'math', grade: 'chu1', term: 'first', text: `5 × a × a × b を文字式の表し方の決まりにしたがって書くとどうなるか。`, choices: ["5aab","5a²b","5ab²","25ab"], correctIndex: 1, explanation: `数は文字の前に、同じ文字は累乗で、アルファベット順に並べます。` },

  // 数量の表し方 (71〜80)
  { id: 'math-chu1-first-0071', subject: 'math', grade: 'chu1', term: 'first', text: `1個 x 円のりんご3個と、1個 y 円のみかん2個を買ったときの合計代金を表す式はどれか。`, choices: ["3x + 2y (円)","x + y + 5 (円)","6xy (円)","3x - 2y (円)"], correctIndex: 0, explanation: `りんごの代金が3x円、みかんの代金が2y円で、その合計なので 3x + 2y となります。` },
  { id: 'math-chu1-first-0072', subject: 'math', grade: 'chu1', term: 'first', text: `a 円の品物を買って、1000円出したときのおつりを表す式はどれか。`, choices: ["a - 1000 (円)","1000a (円)","1000 - a (円)","1000/a (円)"], correctIndex: 2, explanation: `おつりは（出したお金）−（代金）で計算します。` },
  { id: 'math-chu1-first-0073', subject: 'math', grade: 'chu1', term: 'first', text: `時速 x km で 3時間進んだときの道のりを表す式はどれか。`, choices: ["x/3 (km)","3/x (km)","3 + x (km)","3x (km)"], correctIndex: 3, explanation: `道のり ＝ 速さ × 時間 なので、x × 3 = 3x になります。` },
  { id: 'math-chu1-first-0074', subject: 'math', grade: 'chu1', term: 'first', text: `x km の道のりを 2時間で進んだときの速さを表す式はどれか。`, choices: ["x/2 (km/時)","2x (km/時)","2/x (km/時)","x - 2 (km/時)"], correctIndex: 0, explanation: `速さ ＝ 道のり ÷ 時間 なので、x ÷ 2 = x/2 になります。` },
  { id: 'math-chu1-first-0075', subject: 'math', grade: 'chu1', term: 'first', text: `a m の道のりを 分速 50m で進んだときにかかる時間を表す式はどれか。`, choices: ["50a (分)","a/50 (分)","50/a (分)","a - 50 (分)"], correctIndex: 1, explanation: `時間 ＝ 道のり ÷ 速さ なので、a ÷ 50 = a/50 になります。` },
  { id: 'math-chu1-first-0076', subject: 'math', grade: 'chu1', term: 'first', text: `a 円の 10% の金額を表す式はどれか。`, choices: ["10a (円)","0.1a (円)","0.01a (円)","a - 10 (円)"], correctIndex: 1, explanation: `10% は 10/100 ＝ 0.1 です。したがって 0.1a（または 10a/100）となります。` },
  { id: 'math-chu1-first-0077', subject: 'math', grade: 'chu1', term: 'first', text: `x 円の 3割 の金額を表す式はどれか。`, choices: ["3x (円)","0.03x (円)","0.3x (円)","x - 3 (円)"], correctIndex: 2, explanation: `3割 は 3/10 ＝ 0.3 です。したがって 0.3x（または 3x/10）となります。` },
  { id: 'math-chu1-first-0078', subject: 'math', grade: 'chu1', term: 'first', text: `定価 a 円の品物を 2割引で買うときの代金を表す式はどれか。`, choices: ["0.2a (円)","1.2a (円)","0.8a (円)","a - 2 (円)"], correctIndex: 2, explanation: `2割引ということは、定価の8割（80%）で買うことになります。したがって 0.8a となります。` },
  { id: 'math-chu1-first-0079', subject: 'math', grade: 'chu1', term: 'first', text: `底辺が a cm、高さが h cm の三角形の面積を表す式はどれか。`, choices: ["ah (cm²)","2ah (cm²)","1/2 ah (cm²)","a+h (cm²)"], correctIndex: 2, explanation: `三角形の面積は（底辺 × 高さ ÷ 2）なので、1/2 ah になります。` },
  { id: 'math-chu1-first-0080', subject: 'math', grade: 'chu1', term: 'first', text: `百の位が a、十の位が b、一の位が c の3けたの自然数を表す式はどれか。`, choices: ["a + b + c","abc","100a + 10b + c","100a + b + c"], correctIndex: 2, explanation: `位取りの原理から、百の位の数に100、十の位の数に10をかけて一の位を足します。` },

  // 式の値 (81〜90)
  { id: 'math-chu1-first-0081', subject: 'math', grade: 'chu1', term: 'first', text: `x = 3 のとき、式 2x + 1 の値はいくつか。`, choices: ["6","7","5","24"], correctIndex: 1, explanation: `2 × 3 + 1 = 6 + 1 = 7 です。` },
  { id: 'math-chu1-first-0082', subject: 'math', grade: 'chu1', term: 'first', text: `a = -2 のとき、式 5a - 3 の値はいくつか。`, choices: ["-7","-13","7","13"], correctIndex: 1, explanation: `5 × (-2) - 3 = -10 - 3 = -13 です。` },
  { id: 'math-chu1-first-0083', subject: 'math', grade: 'chu1', term: 'first', text: `x = -4 のとき、式 -3x + 2 の値はいくつか。`, choices: ["-10","14","-14","10"], correctIndex: 1, explanation: `-3 × (-4) + 2 = 12 + 2 = 14 です。` },
  { id: 'math-chu1-first-0084', subject: 'math', grade: 'chu1', term: 'first', text: `x = 5 のとき、式 10 - x の値はいくつか。`, choices: ["15","5","-5","50"], correctIndex: 1, explanation: `10 - 5 = 5 です。` },
  { id: 'math-chu1-first-0085', subject: 'math', grade: 'chu1', term: 'first', text: `a = -3 のとき、式 a² の値はいくつか。`, choices: ["-9","9","-6","6"], correctIndex: 1, explanation: `(-3)² = (-3) × (-3) = 9 です。` },
  { id: 'math-chu1-first-0086', subject: 'math', grade: 'chu1', term: 'first', text: `a = -3 のとき、式 -a² の値はいくつか。`, choices: ["9","-9","6","-6"], correctIndex: 1, explanation: `- (-3)² = - (9) = -9 です。` },
  { id: 'math-chu1-first-0087', subject: 'math', grade: 'chu1', term: 'first', text: `x = 2, y = -3 のとき、式 3x + y の値はいくつか。`, choices: ["3","9","-3","-9"], correctIndex: 0, explanation: `3 × 2 + (-3) = 6 - 3 = 3 です。` },
  { id: 'math-chu1-first-0088', subject: 'math', grade: 'chu1', term: 'first', text: `x = -1, y = 4 のとき、式 2x - 3y の値はいくつか。`, choices: ["10","-14","14","-10"], correctIndex: 1, explanation: `2 × (-1) - 3 × 4 = -2 - 12 = -14 です。` },
  { id: 'math-chu1-first-0089', subject: 'math', grade: 'chu1', term: 'first', text: `x = 3 のとき、式 x² - 4x の値はいくつか。`, choices: ["-3","3","21","-21"], correctIndex: 0, explanation: `3² - 4 × 3 = 9 - 12 = -3 です。` },
  { id: 'math-chu1-first-0090', subject: 'math', grade: 'chu1', term: 'first', text: `a = 4 のとき、式 12/a の値はいくつか。`, choices: ["8","3","48","1/3"], correctIndex: 1, explanation: `12 ÷ 4 = 3 です。` },

  // 文字式の計算 (91〜100)
  { id: 'math-chu1-first-0091', subject: 'math', grade: 'chu1', term: 'first', text: `3x + 2x を計算しなさい。`, choices: ["6x²","5x","x","5x²"], correctIndex: 1, explanation: `(3 + 2)x = 5x と同類項をまとめます。` },
  { id: 'math-chu1-first-0092', subject: 'math', grade: 'chu1', term: 'first', text: `5a - 8a を計算しなさい。`, choices: ["-3a","3a","-13a","13a"], correctIndex: 0, explanation: `(5 - 8)a = -3a となります。` },
  { id: 'math-chu1-first-0093', subject: 'math', grade: 'chu1', term: 'first', text: `4x + 7 - 2x - 3 を計算しなさい。`, choices: ["6x + 4","2x - 10","2x + 4","6x - 10"], correctIndex: 2, explanation: `xの項と数の項をそれぞれまとめます。 (4 - 2)x + (7 - 3) = 2x + 4。` },
  { id: 'math-chu1-first-0094', subject: 'math', grade: 'chu1', term: 'first', text: `-a + 5 + 3a - 9 を計算しなさい。`, choices: ["2a - 4","4a - 4","2a + 14","4a + 14"], correctIndex: 0, explanation: `(-1 + 3)a + (5 - 9) = 2a - 4 となります。` },
  { id: 'math-chu1-first-0095', subject: 'math', grade: 'chu1', term: 'first', text: `2(3x + 4) を計算しなさい。`, choices: ["6x + 4","5x + 6","6x + 8","5x + 4"], correctIndex: 2, explanation: `分配法則を使ってカッコをはずします。2×3x + 2×4 = 6x + 8。` },
  { id: 'math-chu1-first-0096', subject: 'math', grade: 'chu1', term: 'first', text: `-3(2a - 5) を計算しなさい。`, choices: ["-6a - 15","-6a + 15","6a - 15","6a + 15"], correctIndex: 1, explanation: `-3×2a - 3×(-5) = -6a + 15 となります。` },
  { id: 'math-chu1-first-0097', subject: 'math', grade: 'chu1', term: 'first', text: `4(x + 2) + 3(2x - 1) を計算しなさい。`, choices: ["10x + 11","10x + 5","2x + 5","10x - 5"], correctIndex: 1, explanation: `(4x + 8) + (6x - 3) = 10x + 5 となります。` },
  { id: 'math-chu1-first-0098', subject: 'math', grade: 'chu1', term: 'first', text: `5(2a - 3) - 2(3a - 4) を計算しなさい。`, choices: ["4a - 23","4a - 7","16a - 7","16a - 23"], correctIndex: 1, explanation: `(10a - 15) - (6a - 8) = 10a - 15 - 6a + 8 = 4a - 7 となります。` },
  { id: 'math-chu1-first-0099', subject: 'math', grade: 'chu1', term: 'first', text: `(12x - 8) ÷ 4 を計算しなさい。`, choices: ["3x - 8","12x - 2","3x - 2","8x - 4"], correctIndex: 2, explanation: `それぞれの項を4で割ります。12x÷4 - 8÷4 = 3x - 2。` },
  { id: 'math-chu1-first-0100', subject: 'math', grade: 'chu1', term: 'first', text: `(6a + 9) ÷ (-3) を計算しなさい。`, choices: ["-2a - 3","-2a + 3","2a - 3","2a + 3"], correctIndex: 0, explanation: `それぞれの項を-3で割ります。6a÷(-3) + 9÷(-3) = -2a - 3。` }
];