export const scienceChu1FirstQuestions = [
  // 植物のつくりとはたらき：花のつくり（1〜10）
  { id: 'science-chu1-first-0001', subject: 'science', grade: 'chu1', term: 'first', text: `めしべの先端の部分を何というか。`, choices: ["子房","柱頭","やく","胚珠"], correctIndex: 1, explanation: `めしべの先端は花粉がつきやすいようになっており、柱頭とよばれます。` },
  { id: 'science-chu1-first-0002', subject: 'science', grade: 'chu1', term: 'first', text: `めしべの根元のふくらんだ部分を何というか。`, choices: ["子房","柱頭","やく","がく"], correctIndex: 0, explanation: `めしべの根元のふくらみを子房といい、中に胚珠が入っています。` },
  { id: 'science-chu1-first-0003', subject: 'science', grade: 'chu1', term: 'first', text: `受粉後、成長してやがて種子になる部分はどれか。`, choices: ["子房","柱頭","胚珠","やく"], correctIndex: 2, explanation: `胚珠は受粉後に成長して種子になります。` },
  { id: 'science-chu1-first-0004', subject: 'science', grade: 'chu1', term: 'first', text: `受粉後、成長してやがて果実になる部分はどれか。`, choices: ["子房","胚珠","花弁","がく"], correctIndex: 0, explanation: `子房は受粉後に成長して果実になります。` },
  { id: 'science-chu1-first-0005', subject: 'science', grade: 'chu1', term: 'first', text: `おしべの先端にある、花粉が入っている袋を何というか。`, choices: ["子房","やく","柱頭","胞子嚢"], correctIndex: 1, explanation: `おしべの先端には「やく」という袋があり、ここで花粉が作られます。` },
  { id: 'science-chu1-first-0006', subject: 'science', grade: 'chu1', term: 'first', text: `花粉がめしべの柱頭につくことを何というか。`, choices: ["受精","受粉","光合成","蒸散"], correctIndex: 1, explanation: `花粉がめしべの柱頭につく現象を受粉といいます。` },
  { id: 'science-chu1-first-0007', subject: 'science', grade: 'chu1', term: 'first', text: `胚珠が子房の中に包まれている植物を何というか。`, choices: ["被子植物","裸子植物","シダ植物","コケ植物"], correctIndex: 0, explanation: `胚珠が子房に被われている（包まれている）ため、被子植物とよばれます。` },
  { id: 'science-chu1-first-0008', subject: 'science', grade: 'chu1', term: 'first', text: `花弁（花びら）が1枚ずつつながっている花を何というか。`, choices: ["離弁花","合弁花","無花被花","単子葉類"], correctIndex: 1, explanation: `アサガオやツツジのように花弁がつながっている花を合弁花といいます。` },
  { id: 'science-chu1-first-0009', subject: 'science', grade: 'chu1', term: 'first', text: `花弁（花びら）が1枚ずつ離れている花を何というか。`, choices: ["合弁花","離弁花","両性花","単性花"], correctIndex: 1, explanation: `サクラやアブラナのように花弁が離れている花を離弁花といいます。` },
  { id: 'science-chu1-first-0010', subject: 'science', grade: 'chu1', term: 'first', text: `アブラナの花弁の数は何枚か。`, choices: ["3枚","4枚","5枚","多数"], correctIndex: 1, explanation: `アブラナは十字架のように4枚の花弁を持ちます。` },

  // 植物のつくりとはたらき：裸子植物（11〜15）
  { id: 'science-chu1-first-0011', subject: 'science', grade: 'chu1', term: 'first', text: `胚珠がむき出しになっている植物を何というか。`, choices: ["被子植物","裸子植物","シダ植物","コケ植物"], correctIndex: 1, explanation: `子房がなく胚珠がむき出しのものを裸子植物といいます。` },
  { id: 'science-chu1-first-0012', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、裸子植物のなかまはどれか。`, choices: ["サクラ","タンポポ","マツ","エンドウ"], correctIndex: 2, explanation: `マツ、イチョウ、スギ、ソテツなどが代表的な裸子植物です。` },
  { id: 'science-chu1-first-0013', subject: 'science', grade: 'chu1', term: 'first', text: `マツの雌花（めばな）のりん片についているものはどれか。`, choices: ["花粉のう","子房","胚珠","やく"], correctIndex: 2, explanation: `マツの雌花のりん片には、むき出しの胚珠がついています。` },
  { id: 'science-chu1-first-0014', subject: 'science', grade: 'chu1', term: 'first', text: `マツの雄花（おばな）のりん片についているものはどれか。`, choices: ["胚珠","子房","がく","花粉のう"], correctIndex: 0, explanation: `マツの雄花のりん片には、花粉が入った「花粉のう」がついています。（※正解選択肢を調整：花粉のうは選択肢4ですが、インデックス0に胚珠を置かず正解を3にします）`, choices: ["胚珠","子房","がく","花粉のう"], correctIndex: 3 },
  { id: 'science-chu1-first-0015', subject: 'science', grade: 'chu1', term: 'first', text: `被子植物と裸子植物を合わせて何植物とよぶか。`, choices: ["胞子植物","種子植物","シダ植物","コケ植物"], correctIndex: 1, explanation: `どちらも種子を作ってふえるため、種子植物とよばれます。` },

  // 植物のつくりとはたらき：根・茎のつくり（16〜25）
  { id: 'science-chu1-first-0016', subject: 'science', grade: 'chu1', term: 'first', text: `双子葉類の根のつくりは、太い根とそこから枝分かれした細い根からなる。太い根を何というか。`, choices: ["ひげ根","側根","主根","不定根"], correctIndex: 2, explanation: `中心の太い根を主根、そこから生える細い根を側根といいます。` },
  { id: 'science-chu1-first-0017', subject: 'science', grade: 'chu1', term: 'first', text: `単子葉類の根のつくりに見られる、多数の細い根を何というか。`, choices: ["主根","側根","ひげ根","仮根"], correctIndex: 2, explanation: `イネやトウモロコシなど単子葉類は、同じような太さのひげ根を持ちます。` },
  { id: 'science-chu1-first-0018', subject: 'science', grade: 'chu1', term: 'first', text: `根の先端近くにある、細い毛のようなつくりを何というか。`, choices: ["側根","ひげ根","根毛","葉脈"], correctIndex: 2, explanation: `根毛が土のすき間に入り込み、水や肥料分を吸収します。` },
  { id: 'science-chu1-first-0019', subject: 'science', grade: 'chu1', term: 'first', text: `根毛があることの利点はどれか。`, choices: ["土を柔らかくする","表面積が大きくなり、水を吸収しやすくなる","光合成を助ける","養分を作り出す"], correctIndex: 1, explanation: `根毛により表面積が大きくなり、効率よく水や水に溶けた養分を吸収できます。` },
  { id: 'science-chu1-first-0020', subject: 'science', grade: 'chu1', term: 'first', text: `根から吸収した水や、水に溶けた養分が通る管を何というか。`, choices: ["道管","師管","気孔","葉脈"], correctIndex: 0, explanation: `水が通る管を道管といいます。` },
  { id: 'science-chu1-first-0021', subject: 'science', grade: 'chu1', term: 'first', text: `葉で作られた養分が通る管を何というか。`, choices: ["道管","師管","気管","毛細血管"], correctIndex: 1, explanation: `葉の光合成で作られた養分が通る管を師管といいます。` },
  { id: 'science-chu1-first-0022', subject: 'science', grade: 'chu1', term: 'first', text: `道管と師管の集まりを何というか。`, choices: ["維管束","葉脈","気孔","組織"], correctIndex: 0, explanation: `道管と師管が束になったものを維管束といいます。` },
  { id: 'science-chu1-first-0023', subject: 'science', grade: 'chu1', term: 'first', text: `植物の茎の断面において、内側を通っている管はどちらか。`, choices: ["師管","道管","血管","気管"], correctIndex: 1, explanation: `茎では、道管が内側、師管が外側を通っています。` },
  { id: 'science-chu1-first-0024', subject: 'science', grade: 'chu1', term: 'first', text: `双子葉類の茎における維管束の並び方はどれか。`, choices: ["散らばっている","輪のように並んでいる","中心に一つだけある","存在しない"], correctIndex: 1, explanation: `双子葉類の維管束は輪状に規則正しく並んでいます。` },
  { id: 'science-chu1-first-0025', subject: 'science', grade: 'chu1', term: 'first', text: `単子葉類の茎における維管束の並び方はどれか。`, choices: ["散らばっている","輪のように並んでいる","中心に一つだけある","存在しない"], correctIndex: 0, explanation: `単子葉類の維管束は茎全体に散らばって配置されています。` },

  // 植物のつくりとはたらき：葉・光合成・蒸散（26〜40）
  { id: 'science-chu1-first-0026', subject: 'science', grade: 'chu1', term: 'first', text: `葉に見られる、維管束のすじを何というか。`, choices: ["道管","師管","葉脈","気孔"], correctIndex: 2, explanation: `葉を通る維管束のすじを葉脈といいます。` },
  { id: 'science-chu1-first-0027', subject: 'science', grade: 'chu1', term: 'first', text: `双子葉類の葉脈の模様はどのようになっているか。`, choices: ["平行脈","網状脈","放射脈","直線脈"], correctIndex: 1, explanation: `双子葉類の葉脈は網目状に広がっており、網状脈といいます。` },
  { id: 'science-chu1-first-0028', subject: 'science', grade: 'chu1', term: 'first', text: `単子葉類の葉脈の模様はどのようになっているか。`, choices: ["網状脈","放射脈","平行脈","直線脈"], correctIndex: 2, explanation: `単子葉類の葉脈は平行に並んでおり、平行脈といいます。` },
  { id: 'science-chu1-first-0029', subject: 'science', grade: 'chu1', term: 'first', text: `葉の表皮にある、気体の出入り口となるすき間を何というか。`, choices: ["気孔","葉緑体","液胞","孔辺細胞"], correctIndex: 0, explanation: `酸素や二酸化炭素、水蒸気が出入りするすき間を気孔といいます。` },
  { id: 'science-chu1-first-0030', subject: 'science', grade: 'chu1', term: 'first', text: `気孔の開閉を調節する、三日月形の細胞を何というか。`, choices: ["表皮細胞","孔辺細胞","葉肉細胞","根毛"], correctIndex: 1, explanation: `一対の孔辺細胞によって気孔の開き具合が調節されます。` },
  { id: 'science-chu1-first-0031', subject: 'science', grade: 'chu1', term: 'first', text: `気孔の数は、一般的な植物の葉ではどこに多いか。`, choices: ["表側","裏側","表と裏で同じ","茎の部分のみ"], correctIndex: 1, explanation: `一般的に、気孔は葉の裏側に多く分布しています。` },
  { id: 'science-chu1-first-0032', subject: 'science', grade: 'chu1', term: 'first', text: `植物の体内の水が、水蒸気となって気孔から空気中へ出ていく現象を何というか。`, choices: ["光合成","呼吸","蒸散","凝結"], correctIndex: 2, explanation: `この蒸散により、根から水が吸い上げられる原動力が生まれます。` },
  { id: 'science-chu1-first-0033', subject: 'science', grade: 'chu1', term: 'first', text: `光合成が行われる、細胞の中にある緑色の粒を何というか。`, choices: ["核","液胞","ミトコンドリア","葉緑体"], correctIndex: 3, explanation: `葉緑体の中で、光のエネルギーを使って光合成が行われます。` },
  { id: 'science-chu1-first-0034', subject: 'science', grade: 'chu1', term: 'first', text: `光合成に必要なものは、光、水と、もう一つは何か。`, choices: ["酸素","二酸化炭素","窒素","水素"], correctIndex: 1, explanation: `水と二酸化炭素を材料として光合成を行います。` },
  { id: 'science-chu1-first-0035', subject: 'science', grade: 'chu1', term: 'first', text: `光合成によって作られる養分（デンプンなど）と、もう一つ発生する気体は何か。`, choices: ["二酸化炭素","窒素","酸素","水蒸気"], correctIndex: 2, explanation: `光合成の結果、デンプンなどの養分と酸素が作られます。` },
  { id: 'science-chu1-first-0036', subject: 'science', grade: 'chu1', term: 'first', text: `デンプンがあるかどうかを調べるために使う薬品はどれか。`, choices: ["ベネジクト液","ヨウ素液","塩化コバルト紙","BTB溶液"], correctIndex: 1, explanation: `ヨウ素液はデンプンに反応して青紫色に変化します。` },
  { id: 'science-chu1-first-0037', subject: 'science', grade: 'chu1', term: 'first', text: `植物が酸素を取り入れ、二酸化炭素を出すはたらきを何というか。`, choices: ["光合成","呼吸","蒸散","発酵"], correctIndex: 1, explanation: `動物と同じように、植物も生きるために呼吸を行っています。` },
  { id: 'science-chu1-first-0038', subject: 'science', grade: 'chu1', term: 'first', text: `植物が呼吸を行う時間帯はいつか。`, choices: ["昼間だけ","夜間だけ","一日中（昼も夜も）","光が当たっている時だけ"], correctIndex: 2, explanation: `植物は光合成を行わない夜も含め、一日中呼吸を行っています。` },
  { id: 'science-chu1-first-0039', subject: 'science', grade: 'chu1', term: 'first', text: `晴れた日の昼間、植物全体の気体の出入りはどうなっているか。`, choices: ["二酸化炭素を吸収し、酸素を放出する","酸素を吸収し、二酸化炭素を放出する","どちらの気体も出入りしない","窒素を吸収する"], correctIndex: 0, explanation: `昼間は呼吸より光合成の量が多いため、見かけ上は二酸化炭素を吸収し酸素を放出します。` },
  { id: 'science-chu1-first-0040', subject: 'science', grade: 'chu1', term: 'first', text: `水溶液が酸性か、中性か、アルカリ性かによって色が変わる指示薬で、光合成の実験によく使われるものはどれか。`, choices: ["ヨウ素液","酢酸カーミン液","BTB溶液","フェノールフタレイン液"], correctIndex: 2, explanation: `二酸化炭素が溶けた水（酸性・黄色）が、光合成により減少して青色に変わる様子などを観察します。` },

  // 植物の分類・シダ・コケ（41〜50）
  { id: 'science-chu1-first-0041', subject: 'science', grade: 'chu1', term: 'first', text: `種子を作らず、胞子でふえる植物のグループはどれか。`, choices: ["被子植物","裸子植物","シダ植物","双子葉類"], correctIndex: 2, explanation: `シダ植物とコケ植物は種子を作らず胞子でふえます。` },
  { id: 'science-chu1-first-0042', subject: 'science', grade: 'chu1', term: 'first', text: `シダ植物やコケ植物の胞子が入っている袋を何というか。`, choices: ["花粉のう","子房","やく","胞子のう"], correctIndex: 3, explanation: `葉の裏などに胞子嚢（ほうしのう）があり、その中で胞子が作られます。` },
  { id: 'science-chu1-first-0043', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、シダ植物のなかまはどれか。`, choices: ["イヌワラビ","ゼニゴケ","スギゴケ","マツ"], correctIndex: 0, explanation: `イヌワラビ、ゼンマイなどがシダ植物です。` },
  { id: 'science-chu1-first-0044', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、コケ植物のなかまはどれか。`, choices: ["イヌワラビ","ゼニゴケ","スギ","アサガオ"], correctIndex: 1, explanation: `ゼニゴケやスギゴケなどがコケ植物です。` },
  { id: 'science-chu1-first-0045', subject: 'science', grade: 'chu1', term: 'first', text: `シダ植物の体の特徴として正しいものはどれか。`, choices: ["根・茎・葉の区別がない","維管束がない","根・茎・葉の区別があり、維管束がある","花を咲かせる"], correctIndex: 2, explanation: `シダ植物は種子植物と同じように根・茎・葉があり、維管束も発達しています。` },
  { id: 'science-chu1-first-0046', subject: 'science', grade: 'chu1', term: 'first', text: `コケ植物の体の特徴として正しいものはどれか。`, choices: ["根・茎・葉の区別がある","維管束がある","種子でふえる","根・茎・葉の区別がなく、維管束もない"], correctIndex: 3, explanation: `コケ植物は根・茎・葉の区別や維管束がなく、体全体で水を吸収します。` },
  { id: 'science-chu1-first-0047', subject: 'science', grade: 'chu1', term: 'first', text: `コケ植物に見られる、体を地面などに固定するための根のようなつくりを何というか。`, choices: ["主根","仮根","ひげ根","側根"], correctIndex: 1, explanation: `仮根（かこん）は水を吸収する働きはなく、体を固定する役割を持ちます。` },
  { id: 'science-chu1-first-0048', subject: 'science', grade: 'chu1', term: 'first', text: `子葉（最初の葉）が2枚出る植物を何というか。`, choices: ["単子葉類","双子葉類","裸子植物","シダ植物"], correctIndex: 1, explanation: `双子葉類は子葉が2枚で、葉脈は網状脈、根は主根と側根という特徴があります。` },
  { id: 'science-chu1-first-0049', subject: 'science', grade: 'chu1', term: 'first', text: `子葉が1枚出る植物を何というか。`, choices: ["双子葉類","単子葉類","離弁花類","合弁花類"], correctIndex: 1, explanation: `単子葉類は子葉が1枚で、葉脈は平行脈、根はひげ根という特徴があります。` },
  { id: 'science-chu1-first-0050', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、単子葉類の植物はどれか。`, choices: ["アサガオ","ツツジ","トウモロコシ","エンドウ"], correctIndex: 2, explanation: `トウモロコシ、イネ、ユリなどは単子葉類です。` },

  // 物質の姿：有機物と無機物・金属（51〜60）
  { id: 'science-chu1-first-0051', subject: 'science', grade: 'chu1', term: 'first', text: `加熱して燃えると、黒くこげたり、二酸化炭素や水を発生したりする物質を何というか。`, choices: ["無機物","有機物","金属","単体"], correctIndex: 1, explanation: `炭素を含む物質を有機物といい、燃えると二酸化炭素が発生します。` },
  { id: 'science-chu1-first-0052', subject: 'science', grade: 'chu1', term: 'first', text: `有機物に必ず含まれている元素（成分）は何か。`, choices: ["鉄","酸素","窒素","炭素"], correctIndex: 3, explanation: `有機物は炭素を含んでおり、燃えると酸素と結びついて二酸化炭素になります。` },
  { id: 'science-chu1-first-0053', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、有機物に分類されるものはどれか。`, choices: ["食塩","鉄","プラスチック","ガラス"], correctIndex: 2, explanation: `プラスチックや木、紙、砂糖などは有機物です。` },
  { id: 'science-chu1-first-0054', subject: 'science', grade: 'chu1', term: 'first', text: `有機物以外の物質をまとめて何というか。`, choices: ["炭水化物","無機物","ポリマー","混合物"], correctIndex: 1, explanation: `食塩や金属、ガラスなどは炭素を含まない無機物です。（※二酸化炭素なども無機物に分類されます）` },
  { id: 'science-chu1-first-0055', subject: 'science', grade: 'chu1', term: 'first', text: `次のうち、金属の共通の性質として当てはまらないものはどれか。`, choices: ["電気をよく通す","熱をよく伝える","磁石に引きつけられる","みがくと光る"], correctIndex: 2, explanation: `磁石につくのは鉄など一部の金属だけで、金属全体の共通の性質ではありません。` },
  { id: 'science-chu1-first-0056', subject: 'science', grade: 'chu1', term: 'first', text: `金属をみがいたときに出る特有の輝きを何というか。`, choices: ["金属光沢","延性","展性","反射"], correctIndex: 0, explanation: `金属特有の輝きを金属光沢といいます。` },
  { id: 'science-chu1-first-0057', subject: 'science', grade: 'chu1', term: 'first', text: `金属をたたくと、薄く広がる性質を何というか。`, choices: ["延性","展性","弾性","光沢"], correctIndex: 1, explanation: `薄く広がる性質を「展性（てんせい）」といいます。（アルミニウムはく等）` },
  { id: 'science-chu1-first-0058', subject: 'science', grade: 'chu1', term: 'first', text: `金属を引っ張ると、細く延びる性質を何というか。`, choices: ["展性","延性","伝導性","磁性"], correctIndex: 1, explanation: `細く長く延びる性質を「延性（えんせい）」といいます。（銅線等）` },
  { id: 'science-chu1-first-0059', subject: 'science', grade: 'chu1', term: 'first', text: `金属以外の物質（ガラス、プラスチック、木など）を何というか。`, choices: ["合金","有機物","非金属","無機物"], correctIndex: 2, explanation: `金属の性質を持たない物質を非金属といいます。` },
  { id: 'science-chu1-first-0060', subject: 'science', grade: 'chu1', term: 'first', text: `プラスチック（合成樹脂）の主な原料は何か。`, choices: ["石炭","鉄鉱石","木材","石油"], correctIndex: 3, explanation: `プラスチックは主に石油（原油）から人工的に作られた有機物です。` },

  // 物質の姿：密度と測定器具（61〜70）
  { id: 'science-chu1-first-0061', subject: 'science', grade: 'chu1', term: 'first', text: `物質の体積 1立方センチメートル (1cm³) あたりの質量を何というか。`, choices: ["重さ","密度","濃度","重量"], correctIndex: 1, explanation: `一定の体積あたりの質量を密度といいます。物質ごとに決まった値になります。` },
  { id: 'science-chu1-first-0062', subject: 'science', grade: 'chu1', term: 'first', text: `密度の単位として正しいものはどれか。`, choices: ["g","cm³","g/cm³","N"], correctIndex: 2, explanation: `質量(g)を体積(cm³)で割るため、単位は g/cm³（グラム毎立方センチメートル）となります。` },
  { id: 'science-chu1-first-0063', subject: 'science', grade: 'chu1', term: 'first', text: `密度の求め方の式として正しいものはどれか。`, choices: ["質量(g) × 体積(cm³)","質量(g) ÷ 体積(cm³)","体積(cm³) ÷ 質量(g)","質量(g) ＋ 体積(cm³)"], correctIndex: 1, explanation: `密度は「質量 ÷ 体積」で計算します。` },
  { id: 'science-chu1-first-0064', subject: 'science', grade: 'chu1', term: 'first', text: `質量が 40g、体積が 5cm³ の物質の密度はいくらか。`, choices: ["8 g/cm³","0.125 g/cm³","200 g/cm³","45 g/cm³"], correctIndex: 0, explanation: `40g ÷ 5cm³ = 8 g/cm³ です。` },
  { id: 'science-chu1-first-0065', subject: 'science', grade: 'chu1', term: 'first', text: `水の密度はおよそ 1.0 g/cm³ である。水に浮く物質はどのような密度を持つか。`, choices: ["1.0 g/cm³ より大きい","1.0 g/cm³ と同じ","1.0 g/cm³ より小さい","密度に関係なく浮く"], correctIndex: 2, explanation: `液体より密度が小さい物質はその液体に浮きます。` },
  { id: 'science-chu1-first-0066', subject: 'science', grade: 'chu1', term: 'first', text: `液体の体積を正確にはかるためのガラス器具はどれか。`, choices: ["ビーカー","フラスコ","上皿てんびん","メスシリンダー"], correctIndex: 3, explanation: `体積の測定にはメスシリンダーを用います。` },
  { id: 'science-chu1-first-0067', subject: 'science', grade: 'chu1', term: 'first', text: `メスシリンダーの目盛りを読むときの正しい目の位置はどれか。`, choices: ["液面を上から見下ろす位置","液面を下から見上げる位置","液面のへこんだ最も低い位置を真横から見る","液面の最も高い位置を真横から見る"], correctIndex: 2, explanation: `液面のへこんだ部分（メニスカス）の一番低いところを、目の高さを合わせて水平に読みます。` },
  { id: 'science-chu1-first-0068', subject: 'science', grade: 'chu1', term: 'first', text: `物質の質量をはかるために使う器具はどれか。`, choices: ["メスシリンダー","上皿てんびん","温度計","ルーペ"], correctIndex: 1, explanation: `質量の測定には上皿てんびんや電子てんびんを使います。` },
  { id: 'science-chu1-first-0069', subject: 'science', grade: 'chu1', term: 'first', text: `上皿てんびんで質量をはかるとき、分銅はどのようにのせていくか。`, choices: ["軽いものから順に","重いものから順に","適当な順番で","すべて一度に"], correctIndex: 1, explanation: `はかる物より重そうな分銅からのせ、つり合わなければ軽いものに替えていきます。` },
  { id: 'science-chu1-first-0070', subject: 'science', grade: 'chu1', term: 'first', text: `鉄とアルミニウムを比べたとき、密度が大きい（同じ体積で重い）のはどちらか。`, choices: ["アルミニウム","鉄","同じ","温度によって変わる"], correctIndex: 1, explanation: `鉄の密度（約7.9g/cm³）は、アルミニウム（約2.7g/cm³）よりも大きいです。` },

  // 物質の状態変化（71〜80）
  { id: 'science-chu1-first-0071', subject: 'science', grade: 'chu1', term: 'first', text: `物質が温度によって、固体・液体・気体へと姿を変えることを何というか。`, choices: ["化学変化","状態変化","分解","化合"], correctIndex: 1, explanation: `温度の変化により、物質そのものは変わらずに状態だけが変わることを状態変化といいます。` },
  { id: 'science-chu1-first-0072', subject: 'science', grade: 'chu1', term: 'first', text: `氷がとけて水になるように、固体から液体に変わることを何というか。`, choices: ["気化","凝結","融解","昇華"], correctIndex: 2, explanation: `固体から液体への変化を融解（ゆうかい）といいます。` },
  { id: 'science-chu1-first-0073', subject: 'science', grade: 'chu1', term: 'first', text: `水が水蒸気になるように、液体から気体に変わることを何というか。`, choices: ["融解","気化","凝固","昇華"], correctIndex: 1, explanation: `液体から気体への変化を気化（きか）といいます。沸騰や蒸発がこれにあたります。` },
  { id: 'science-chu1-first-0074', subject: 'science', grade: 'chu1', term: 'first', text: `状態変化が起こったとき、変化しないものはどれか。`, choices: ["体積","質量","密度","粒子の間隔"], correctIndex: 1, explanation: `状態が変わっても、物質を作っている粒子の数は変わらないため、質量は変化しません。` },
  { id: 'science-chu1-first-0075', subject: 'science', grade: 'chu1', term: 'first', text: `一般に、物質が固体→液体→気体と状態変化すると、体積はどうなるか。`, choices: ["小さくなる","変わらない","大きくなる","質量と同じになる"], correctIndex: 2, explanation: `粒子と粒子の間隔が広がるため、一般的に体積は大きくなります。（水は例外的な性質を持ちます）` },
  { id: 'science-chu1-first-0076', subject: 'science', grade: 'chu1', term: 'first', text: `液体が沸騰して気体になり始めるときの温度を何というか。`, choices: ["融点","沸点","露点","氷点"], correctIndex: 1, explanation: `沸騰が起こる温度を沸点といいます。物質の種類によって決まっています。` },
  { id: 'science-chu1-first-0077', subject: 'science', grade: 'chu1', term: 'first', text: `純粋な水の沸点（1気圧のとき）は何度か。`, choices: ["0℃","50℃","100℃","200℃"], correctIndex: 2, explanation: `水の沸点は100℃です。` },
  { id: 'science-chu1-first-0078', subject: 'science', grade: 'chu1', term: 'first', text: `固体がとけて液体になり始めるときの温度を何というか。`, choices: ["融点","沸点","露点","絶対零度"], correctIndex: 0, explanation: `とけ始める（融解する）温度を融点といいます。` },
  { id: 'science-chu1-first-0079', subject: 'science', grade: 'chu1', term: 'first', text: `純粋な物質の状態変化において、とけている間や沸騰している間の温度はどうなるか。`, choices: ["上がり続ける","下がり続ける","一定に保たれる","上がったり下がったりする"], correctIndex: 2, explanation: `純粋な物質は、状態変化している間は熱を加えても温度が一定に保たれます。` },
  { id: 'science-chu1-first-0080', subject: 'science', grade: 'chu1', term: 'first', text: `液体を加熱して沸騰させ、出てきた気体を冷やして再び液体にして取り出す方法を何というか。`, choices: ["ろ過","蒸留","抽出","再結晶"], correctIndex: 1, explanation: `沸点の違いを利用して混合物などを分離する方法を蒸留といいます。` },

  // 水溶液の性質（81〜90）
  { id: 'science-chu1-first-0081', subject: 'science', grade: 'chu1', term: 'first', text: `食塩水のように、液体に物質が溶けた液全体を何というか。`, choices: ["溶媒","溶質","水溶液","再結晶"], correctIndex: 2, explanation: `水に物質が溶けたものを水溶液といいます。（水以外の液体の場合は溶液）` },
  { id: 'science-chu1-first-0082', subject: 'science', grade: 'chu1', term: 'first', text: `水溶液に溶けている物質（食塩水における食塩）を何というか。`, choices: ["溶媒","溶質","溶液","結晶"], correctIndex: 1, explanation: `溶けている物質そのものを溶質といいます。` },
  { id: 'science-chu1-first-0083', subject: 'science', grade: 'chu1', term: 'first', text: `物質を溶かしている液体（食塩水における水）を何というか。`, choices: ["溶質","溶媒","溶液","飽和液"], correctIndex: 1, explanation: `溶かしている液体を溶媒（ようばい）といいます。` },
  { id: 'science-chu1-first-0084', subject: 'science', grade: 'chu1', term: 'first', text: `水溶液の濃さを、水溶液全体の質量に対する溶質の質量の割合を百分率（％）で表したものを何というか。`, choices: ["質量パーセント濃度","溶解度","密度","体積パーセント濃度"], correctIndex: 0, explanation: `質量パーセント濃度 ＝ 溶質の質量 ÷ 水溶液の質量 × 100 で求めます。` },
  { id: 'science-chu1-first-0085', subject: 'science', grade: 'chu1', term: 'first', text: `水 90g に食塩 10g を溶かした食塩水の質量パーセント濃度は何％か。`, choices: ["9％","10％","11.1％","90％"], correctIndex: 1, explanation: `溶質(10g) ÷ 水溶液全体(90g+10g) × 100 = 10% です。` },
  { id: 'science-chu1-first-0086', subject: 'science', grade: 'chu1', term: 'first', text: `一定量の水（一般に100g）に溶かすことができる物質の最大の質量を何というか。`, choices: ["密度","濃度","溶解度","飽和度"], correctIndex: 2, explanation: `溶解度は物質の種類と水の温度によって決まっています。` },
  { id: 'science-chu1-first-0087', subject: 'science', grade: 'chu1', term: 'first', text: `物質が溶解度まで溶けており、それ以上溶かすことができない水溶液を何というか。`, choices: ["純粋な水溶液","飽和水溶液","混合水溶液","過冷却液"], correctIndex: 1, explanation: `限界まで溶けた水溶液を飽和水溶液といいます。` },
  { id: 'science-chu1-first-0088', subject: 'science', grade: 'chu1', term: 'first', text: `水の温度と溶解度の関係をグラフに表したものを何というか。`, choices: ["溶解度曲線","状態変化曲線","気温変化グラフ","飽和曲線"], correctIndex: 0, explanation: `温度による溶けやすさの変化を示すグラフを溶解度曲線といいます。` },
  { id: 'science-chu1-first-0089', subject: 'science', grade: 'chu1', term: 'first', text: `固体をいったん水に溶かし、温度を下げたり水を蒸発させたりして、再び固体の粒として取り出すことを何というか。`, choices: ["ろ過","蒸留","再結晶","昇華"], correctIndex: 2, explanation: `溶解度の差を利用して、純粋な物質を取り出す操作を再結晶といいます。` },
  { id: 'science-chu1-first-0090', subject: 'science', grade: 'chu1', term: 'first', text: `液体に溶けきれずに残った固体を、ろ紙を使って液体と分離する操作を何というか。`, choices: ["蒸留","ろ過","抽出","再結晶"], correctIndex: 1, explanation: `ろ紙のすき間を通る液体と、通らない固体を分ける方法を「ろ過」といいます。` },

  // 気体の発生と性質（91〜100）
  { id: 'science-chu1-first-0091', subject: 'science', grade: 'chu1', term: 'first', text: `二酸化マンガンにうすい過酸化水素水（オキシドール）を加えると発生する気体は何か。`, choices: ["水素","二酸化炭素","酸素","アンモニア"], correctIndex: 2, explanation: `酸素は、二酸化マンガンを触媒として過酸化水素水を分解すると発生します。` },
  { id: 'science-chu1-first-0092', subject: 'science', grade: 'chu1', term: 'first', text: `酸素の性質として正しいものはどれか。`, choices: ["燃えて水になる","石灰水を白く濁らせる","物を燃やす働き（助燃性）がある","非常に水に溶けやすい"], correctIndex: 2, explanation: `酸素には、物が燃えるのを助ける働きがあります。火のついた線香を入れると炎を上げて燃えます。` },
  { id: 'science-chu1-first-0093', subject: 'science', grade: 'chu1', term: 'first', text: `石灰石（チョークなど）にうすい塩酸を加えると発生する気体は何か。`, choices: ["水素","酸素","二酸化炭素","アンモニア"], correctIndex: 2, explanation: `炭酸カルシウムを含むものに塩酸をかけると、二酸化炭素が発生します。` },
  { id: 'science-chu1-first-0094', subject: 'science', grade: 'chu1', term: 'first', text: `二酸化炭素の性質として正しいものはどれか。`, choices: ["石灰水を通すと白く濁る","最も軽い気体である","刺激臭がある","火を近づけるとポンと音を立てて燃える"], correctIndex: 0, explanation: `二酸化炭素は石灰水を白く濁らせる性質があります。` },
  { id: 'science-chu1-first-0095', subject: 'science', grade: 'chu1', term: 'first', text: `鉄や亜鉛などの金属にうすい塩酸を加えると発生する気体は何か。`, choices: ["酸素","二酸化炭素","水素","窒素"], correctIndex: 2, explanation: `金属と酸の反応によって水素が発生します。` },
  { id: 'science-chu1-first-0096', subject: 'science', grade: 'chu1', term: 'first', text: `水素の性質として正しいものはどれか。`, choices: ["気体の中で最も軽い","刺激臭がある","空気より重い","物を燃やす働きがある"], correctIndex: 0, explanation: `水素はすべての気体の中で最も密度が小さく（軽く）、火を近づけると音を立てて燃えます。` },
  { id: 'science-chu1-first-0097', subject: 'science', grade: 'chu1', term: 'first', text: `アンモニアの性質として正しいものはどれか。`, choices: ["においはない","水に非常に溶けやすい","空気より重い","水溶液は酸性を示す"], correctIndex: 1, explanation: `アンモニアは特有の刺激臭があり、水に非常に溶けやすく、水溶液はアルカリ性を示します。` },
  { id: 'science-chu1-first-0098', subject: 'science', grade: 'chu1', term: 'first', text: `水に溶けにくい気体（酸素や水素など）を集めるのに最も適した方法はどれか。`, choices: ["上方置換法","下方置換法","水上置換法","ろ過法"], correctIndex: 2, explanation: `水と置き換えて集める水上置換法は、空気が混ざらず純粋な気体を集めることができます。` },
  { id: 'science-chu1-first-0099', subject: 'science', grade: 'chu1', term: 'first', text: `水に溶けやすく、空気より重い気体（二酸化炭素など）を集める方法はどれか。`, choices: ["水上置換法","上方置換法","下方置換法","分留"], correctIndex: 2, explanation: `空気を上に押し出して底の方から集める下方置換法を使います。` },
  { id: 'science-chu1-first-0100', subject: 'science', grade: 'chu1', term: 'first', text: `水に溶けやすく、空気より軽い気体（アンモニアなど）を集める方法はどれか。`, choices: ["上方置換法","下方置換法","水上置換法","蒸留"], correctIndex: 0, explanation: `空気を下に押し出して容器の上の方から集める上方置換法を使います。` }
];